// ===========================
// constants/employerData.js
// Mock data dành riêng cho nhà tuyển dụng
// ===========================

export const mockEmployerProfile = {
  id: "emp1",
  name: "FPT Software",
  email: "hr@fpt.com.vn",
  phone: "024 7300 0123",
  role: "employer",
  logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/FPT_logo_2010.svg/200px-FPT_logo_2010.svg.png",
  coverImage: null,
  website: "https://fpt-software.com",
  industry: "Công nghệ thông tin",
  size: "1000-5000 nhân viên",
  founded: "1999",
  location: "Hà Nội",
  address: "Tầng 2-4, FPT Cầu Giấy, Hà Nội",
  description:
    "FPT Software là công ty công nghệ thông tin hàng đầu Việt Nam, cung cấp dịch vụ phát triển phần mềm, chuyển đổi số và tư vấn CNTT cho khách hàng toàn cầu.",
  verified: true,
  taxCode: "0101247220",
  totalJobs: 24,
  totalApplications: 312,
  totalHired: 87,
};

export const mockPostedJobs = [
  {
    id: "pj1",
    title: "Senior Frontend Developer (ReactJS)",
    status: "active", // active | paused | closed | draft
    category: "IT - Phần mềm",
    location: "Hà Nội",
    salary: { min: 25000000, max: 45000000, currency: "VND" },
    experience: "3-5 năm",
    jobType: "full-time",
    deadline: "2025-05-30",
    postedAt: "2025-04-15",
    applications: 87,
    views: 1240,
    skills: ["ReactJS", "TypeScript", "Redux"],
    urgent: true,
    hot: true,
  },
  {
    id: "pj2",
    title: "Backend Developer (Node.js)",
    status: "active",
    category: "IT - Phần mềm",
    location: "Hồ Chí Minh",
    salary: { min: 20000000, max: 35000000, currency: "VND" },
    experience: "2-4 năm",
    jobType: "full-time",
    deadline: "2025-06-10",
    postedAt: "2025-04-10",
    applications: 54,
    views: 890,
    skills: ["Node.js", "MongoDB", "Docker"],
    urgent: false,
    hot: false,
  },
  {
    id: "pj3",
    title: "UI/UX Designer",
    status: "paused",
    category: "Thiết kế",
    location: "Hà Nội",
    salary: { min: 15000000, max: 25000000, currency: "VND" },
    experience: "1-3 năm",
    jobType: "full-time",
    deadline: "2025-05-15",
    postedAt: "2025-03-28",
    applications: 23,
    views: 450,
    skills: ["Figma", "Adobe XD"],
    urgent: false,
    hot: false,
  },
  {
    id: "pj4",
    title: "DevOps Engineer",
    status: "closed",
    category: "IT - Phần mềm",
    location: "Hà Nội",
    salary: { min: 28000000, max: 50000000, currency: "VND" },
    experience: "3-5 năm",
    jobType: "full-time",
    deadline: "2025-04-01",
    postedAt: "2025-03-01",
    applications: 41,
    views: 760,
    skills: ["AWS", "Kubernetes", "Terraform"],
    urgent: false,
    hot: false,
  },
  {
    id: "pj5",
    title: "Product Manager (Fintech)",
    status: "draft",
    category: "Quản lý sản phẩm",
    location: "Hà Nội",
    salary: { min: 35000000, max: 60000000, currency: "VND" },
    experience: "4-6 năm",
    jobType: "full-time",
    deadline: "2025-07-01",
    postedAt: null,
    applications: 0,
    views: 0,
    skills: ["Product Strategy", "Agile", "SQL"],
    urgent: false,
    hot: false,
  },
];

export const mockApplications = [
  {
    id: "app1",
    jobId: "pj1",
    jobTitle: "Senior Frontend Developer (ReactJS)",
    candidate: {
      id: "c1",
      name: "Nguyễn Văn An",
      email: "an.nguyen@email.com",
      phone: "0912345678",
      avatar: null,
      headline: "Frontend Developer | ReactJS | 3 năm kinh nghiệm",
      location: "Hà Nội",
      education: "Đại học Bách khoa Hà Nội",
      experience: "3 năm",
      skills: ["ReactJS", "TypeScript", "CSS3", "Git"],
    },
    status: "reviewing", // new | reviewing | interviewed | offered | rejected
    appliedAt: "2025-04-16",
    coverLetter:
      "Tôi có 3 năm kinh nghiệm với ReactJS và muốn ứng tuyển vào vị trí này...",
    cvUrl:
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    note: "",
  },
  {
    id: "app2",
    jobId: "pj1",
    jobTitle: "Senior Frontend Developer (ReactJS)",
    candidate: {
      id: "c2",
      name: "Trần Thị Bảo",
      email: "bao.tran@email.com",
      phone: "0987654321",
      avatar: null,
      headline: "Senior Frontend | 5 năm kinh nghiệm | ReactJS + Vue",
      location: "Hà Nội",
      education: "Đại học FPT",
      experience: "5 năm",
      skills: ["ReactJS", "Vue.js", "TypeScript", "Redux", "GraphQL"],
    },
    status: "interviewed",
    appliedAt: "2025-04-14",
    coverLetter: "Tôi có 5 năm kinh nghiệm frontend với stack hiện đại...",
    cvUrl:
      "https://file-examples.com/wp-content/uploads/2017/02/file-sample_100kB.docx",
    note: "Ứng viên tiềm năng, đã phỏng vấn vòng 1",
  },
  {
    id: "app3",
    jobId: "pj1",
    jobTitle: "Senior Frontend Developer (ReactJS)",
    candidate: {
      id: "c3",
      name: "Lê Minh Khoa",
      email: "khoa.le@email.com",
      phone: "0901234567",
      avatar: null,
      headline: "Full-stack Developer | React + Node.js",
      location: "Hồ Chí Minh",
      education: "Đại học Công nghệ HCM",
      experience: "2 năm",
      skills: ["ReactJS", "Node.js", "MongoDB"],
    },
    status: "new",
    appliedAt: "2025-04-18",
    coverLetter: "",
    cvUrl: "https://www.orimi.com/pdf-test.pdf",
    note: "",
  },
  {
    id: "app4",
    jobId: "pj2",
    jobTitle: "Backend Developer (Node.js)",
    candidate: {
      id: "c4",
      name: "Phạm Quốc Dũng",
      email: "dung.pham@email.com",
      phone: "0933445566",
      avatar: null,
      headline: "Backend Engineer | Node.js + MongoDB | 4 năm",
      location: "Hồ Chí Minh",
      education: "Đại học Khoa học tự nhiên HCM",
      experience: "4 năm",
      skills: ["Node.js", "MongoDB", "Redis", "Docker", "AWS"],
    },
    status: "offered",
    appliedAt: "2025-04-11",
    coverLetter: "Với 4 năm kinh nghiệm Node.js và MongoDB...",
    cvUrl:
      "https://file-examples.com/wp-content/uploads/2017/02/file-sample_500kB.doc",
    note: "Đã gửi offer, chờ phản hồi",
  },
  {
    id: "app5",
    jobId: "pj2",
    jobTitle: "Backend Developer (Node.js)",
    candidate: {
      id: "c5",
      name: "Võ Thị Lan Anh",
      email: "lananh.vo@email.com",
      phone: "0944556677",
      avatar: null,
      headline: "Backend Developer | Go + Node.js",
      location: "Hà Nội",
      education: "Học viện Công nghệ Bưu chính Viễn thông",
      experience: "3 năm",
      skills: ["Node.js", "Go", "PostgreSQL", "Docker"],
    },
    status: "rejected",
    appliedAt: "2025-04-09",
    coverLetter: "",
    cvUrl:
      "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-doc.doc",
    note: "Không đáp ứng yêu cầu kỹ năng MongoDB",
  },
];

export const mockDashboardStats = {
  totalJobs: 5,
  activeJobs: 2,
  totalApplications: 205,
  newApplications: 12,
  totalViews: 3340,
  profileViews: 128,
  hiredThisMonth: 3,
  responseRate: 78,
};

export const mockChartData = {
  applicationsByDay: [
    { date: "10/04", count: 8 },
    { date: "11/04", count: 12 },
    { date: "12/04", count: 6 },
    { date: "13/04", count: 15 },
    { date: "14/04", count: 20 },
    { date: "15/04", count: 18 },
    { date: "16/04", count: 25 },
    { date: "17/04", count: 14 },
    { date: "18/04", count: 22 },
    { date: "19/04", count: 9 },
    { date: "20/04", count: 17 },
    { date: "21/04", count: 30 },
  ],
  applicationsByStatus: [
    { status: "Mới", count: 45, color: "#6366f1" },
    { status: "Đang xem xét", count: 80, color: "#f59e0b" },
    { status: "Phỏng vấn", count: 40, color: "#3b82f6" },
    { status: "Đã offer", count: 25, color: "#00b14f" },
    { status: "Từ chối", count: 15, color: "#ef4444" },
  ],
};
